### ISSUE TITLE
Fixt getFixtureLocation does not escape path seperator, causes exception on Windows

### ISSUE THREAD

**Issue by moanrose** [agorapulse/testing-libraries#1]
The parh seeperator is no escaped, which causes an "java.lang.IllegalArgumentException: character to be escaped is missing" on Windows

`Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at com.agorapulse.testing.fixt.Fixt.getFixtureLocation(Fixt.java:138)
	at com.agorapulse.testing.fixt.Fixt.readStreamFromFileSystem(Fixt.java:158)
	at com.agorapulse.testing.fixt.Fixt.readStream(Fixt.java:100)
	at com.agorapulse.gru.AbstractClient.loadFixture(AbstractClient.java:18)
	at com.agorapulse.gru.content.FileContent.load(FileContent.java:24)
	at com.agorapulse.gru.minions.AbstractContentMinion.doVerify(AbstractContentMinion.groovy:34)
	at com.agorapulse.gru.minions.AbstractMinion.verify(AbstractMinion.java:44)
	at com.agorapulse.gru.Squad.verify(Squad.java:117)
	at com.agorapulse.gru.Gru.verify(Gru.java:143)`

**Comment by tlefevre** [comment]
A fix to the problem in PR-2: https://github.com/agorapulse/testing-libraries/pull/2

**Comment by tlefevre** [comment]
https://github.com/agorapulse/testing-libraries/pull/3
